### ISSUE TITLE
'foreman-maintain service stop' causes Pulpcore core dump when database connection lost

### ISSUE THREAD

**Issue by ehelms** [theforeman/foreman_maintain#824] opened 2024-04-09 16:40 UTC
Migrated from https://projects.theforeman.org/issues/37182

Submitted based on community 36512: https://community.theforeman.org/t/pulpcore-coredumps-during-stopping-services/36512

A user is doing some sort of "offline backup" operation which shuts down the database. Afterwards, the user calls 'foreman-maintain service stop', which expects the db endpoint to still be online; this causes a core dump in Pulpcore. Ideally, 'service stop' should be able to handle this edge case without core dumping, whether that is through handling a bad connection or via other means.

Excerpt from messages.log file on community post:

```
Jan 16 04:00:18 hostname pulpcore-content[210923]:  File "/usr/lib/python3.11/site-packages/django/db/backends/postgresql/base.py", line 275, in get_new_connection
Jan 16 04:00:18 hostname pulpcore-content[210923]:    connection = self.Database.connect(**conn_params)
Jan 16 04:00:18 hostname pulpcore-content[210923]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan 16 04:00:18 hostname pulpcore-content[210923]:  File "/usr/lib/python3.11/site-packages/psycopg/connection.py", line 728, in connect
Jan 16 04:00:18 hostname pulpcore-content[210923]:    raise ex.with_traceback(None)
Jan 16 04:00:18 hostname pulpcore-content[210923]: django.db.utils.OperationalError: connection failed: server closed the connection unexpectedly
Jan 16 04:00:18 hostname pulpcore-content[210923]: #011This probably means the server terminated abnormally
Jan 16 04:00:18 hostname pulpcore-content[210923]: #011before or while processing the request.
```

**Comment by ekohl** [comment] 2024-09-12 12:17
I think we should add a `Wants=postgresql.service` to `pulpcore-content.service` so systemd does the right thing. https://github.com/theforeman/puppet-pulpcore/pull/359 should do so.

**Comment by ekohl** [comment] 2024-10-11 16:31
https://community.theforeman.org/t/pulpcore-coredumps-during-stopping-services/36512/8 is the root cause. https://github.com/theforeman/pulpcore-packaging/pull/1361 (and https://github.com/theforeman/pulpcore-packaging/pull/1363 for 3.49) should resolve this. Because it's not in foreman_maintain, I'm closing this issue.

**Closed by ekohl** 2024-10-11 16:31 UTC
